env:
  global:
    - CC_TEST_REPORTER_ID=0453f0568882206e2164bb4f8cbdc014066bf002ec0cc5db3d4956a18c15125c
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT
language: node_js
node_js:
  - "7"
script:
  - npm run codestyle
  - npm run build
  - npm run test
